[ui]
hideTopBar = true

[theme]
base = "light"
primaryColor = "rgb(56, 171, 232)"  # основной цвет
backgroundColor = "rgb(235, 239, 242)"  # белый фон
secondaryBackgroundColor = "rgb(200, 225, 238)"  # светло-серый вторичный фон
textColor = "#181818"  # тёмный цвет текста
#textColor = "#E0E0E0"  # цвет текстаrgb(154, 203, 208)
#font = "sans serif"



#[ui]
#hideTopBar = true

#[theme]
#base = "dark"
#primaryColor = "#4A9A55"  #rgb(129, 207, 233) #808080
#backgroundColor = "#D9EAFD"  # цвет фона
#secondaryBackgroundColor = "#D9EAFD"  # цвет вторичного фона
#textColor = "#E0E0E0"  # цвет текстаrgb(154, 203, 208)
font = "monospace"  #  ['sans serif', 'serif', 'monospace'].