[ui]
hideTopBar = true

[theme]
base = "dark"
primaryColor = "#808080"  # #6C9B6A #808080
backgroundColor = "#2C2C2C"  # цвет фона
secondaryBackgroundColor = "#181818"  # цвет вторичного фона
textColor = "#E0E0E0"  # цвет текста #388E3C
font = "sans serif"  #  ['sans serif', 'serif', 'monospace'].