[ui]
hideTopBar = true

[theme]
base="dark"
primaryColor="#1f77b4"
backgroundColor="#0e1117"  # цвет фона
secondaryBackgroundColor="#262730"  # цвет вторичного фона
textColor="#ffffff"  # цвет текста
font="sans serif"  # шрифт (можно выбрать: "sans serif", "serif", "monospace")


#backgroundColor="#FFFFFF"
##backgroundColor="#000000"
#
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
#font="sans serif"
