[ui]
hideTopBar = true

[theme]
base="light"

primaryColor="#1f77b4"
backgroundColor="#FAEBD7"  # цвет фона
#secondaryBackgroundColor="#FAEBD7"  # цвет вторичного фона
#textColor="#ffffff"  # цвет текста
font="serif"  # шрифт (можно выбрать: "sans serif", "serif", "monospace")


#backgroundColor="#FFFFFF"
##backgroundColor="#000000"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
#font="sans serif"
